// FIFA 2026 World Cup team name to flag emoji mapping
const teamFlags = {
  'Mexico': '🇲🇽',
  'South Africa': '🇿🇦',
  'USA': '🇺🇸',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Brazil': '🇧🇷',
  'Argentina': '🇦🇷',
  'France': '🇫🇷',
  'Germany': '🇩🇪',
  'Spain': '🇪🇸',
  'Portugal': '🇵🇹',
  'Netherlands': '🇳🇱',
  'Belgium': '🇧🇪',
  'Italy': '🇮🇹',
  'Croatia': '🇭🇷',
  'Uruguay': '🇺🇾',
  'Colombia': '🇨🇴',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'Australia': '🇦🇺',
  'Saudi Arabia': '🇸🇦',
  'Iran': '🇮🇷',
  'Qatar': '🇶🇦',
  'Canada': '🇨🇦',
  'Morocco': '🇲🇦',
  'Senegal': '🇸🇳',
  'Ghana': '🇬🇭',
  'Cameroon': '🇨🇲',
  'Nigeria': '🇳🇬',
  'Tunisia': '🇹🇳',
  'Egypt': '🇪🇬',
  'Algeria': '🇩🇿',
  'Ecuador': '🇪🇨',
  'Chile': '🇨🇱',
  'Peru': '🇵🇪',
  'Paraguay': '🇵🇾',
  'Bolivia': '🇧🇴',
  'Venezuela': '🇻🇪',
  'Costa Rica': '🇨🇷',
  'Honduras': '🇭🇳',
  'Panama': '🇵🇦',
  'Jamaica': '🇯🇲',
  'Trinidad and Tobago': '🇹🇹',
  'Serbia': '🇷🇸',
  'Switzerland': '🇨🇭',
  'Denmark': '🇩🇰',
  'Sweden': '🇸🇪',
  'Norway': '🇳🇴',
  'Poland': '🇵🇱',
  'Ukraine': '🇺🇦',
  'Czech Republic': '🇨🇿',
  'Czechia': '🇨🇿',
  'Austria': '🇦🇹',
  'Hungary': '🇭🇺',
  'Romania': '🇷🇴',
  'Greece': '🇬🇷',
  'Turkey': '🇹🇷',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Ireland': '🇮🇪',
  'Republic of Ireland': '🇮🇪',
  'Northern Ireland': '🇬🇧',
  'Iceland': '🇮🇸',
  'Finland': '🇫🇮',
  'Russia': '🇷🇺',
  'China': '🇨🇳',
  'India': '🇮🇳',
  'Indonesia': '🇮🇩',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'New Zealand': '🇳🇿',
  'Ivory Coast': '🇨🇮',
  "Côte d'Ivoire": '🇨🇮',
  'DR Congo': '🇨🇩',
  'Mali': '🇲🇱',
  'Burkina Faso': '🇧🇫',
  'Zambia': '🇿🇲',
  'Zimbabwe': '🇿🇼',
  'Tanzania': '🇹🇿',
  'Kenya': '🇰🇪',
  'Uganda': '🇺🇬',
  'Mozambique': '🇲🇿',
  'Angola': '🇦🇴',
  'Cabo Verde': '🇨🇻',
  'Cape Verde': '🇨🇻',
  'Guatemala': '🇬🇹',
  'El Salvador': '🇸🇻',
  'Cuba': '🇨🇺',
  'Dominican Republic': '🇩🇴',
  'Haiti': '🇭🇹',
  'Uzbekistan': '🇺🇿',
  'Iraq': '🇮🇶',
  'Syria': '🇸🇾',
  'Jordan': '🇯🇴',
  'Palestine': '🇵🇸',
  'Oman': '🇴🇲',
  'UAE': '🇦🇪',
  'United Arab Emirates': '🇦🇪',
  'Bahrain': '🇧🇭',
  'Kuwait': '🇰🇼',
  'Malaysia': '🇲🇾',
  'Philippines': '🇵🇭',
  'Singapore': '🇸🇬',
  'Slovakia': '🇸🇰',
  'Slovenia': '🇸🇮',
  'Bulgaria': '🇧🇬',
  'Albania': '🇦🇱',
  'North Macedonia': '🇲🇰',
  'Montenegro': '🇲🇪',
  'Bosnia and Herzegovina': '🇧🇦',
  'Bosnia': '🇧🇦',
  'Kosovo': '🇽🇰',
  'Georgia': '🇬🇪',
  'Armenia': '🇦🇲',
  'Azerbaijan': '🇦🇿',
  'Kazakhstan': '🇰🇿',
  'Kyrgyzstan': '🇰🇬',
  'Tajikistan': '🇹🇯',
  'Turkmenistan': '🇹🇲',
  'Afghanistan': '🇦🇫',
  'Pakistan': '🇵🇰',
  'Bangladesh': '🇧🇩',
  'Sri Lanka': '🇱🇰',
  'Nepal': '🇳🇵',
  'Myanmar': '🇲🇲',
  'Cambodia': '🇰🇭',
  'Laos': '🇱🇦',
};

export function getFlag(teamName) {
  return teamFlags[teamName] || '🏳️';
}

export default teamFlags;
