// World Cup 2026 team name to ISO country code mapping
const teamCodes = {
  'Mexico': 'mx',
  'South Africa': 'za',
  'USA': 'us',
  'England': 'gb-eng',
  'Brazil': 'br',
  'Argentina': 'ar',
  'France': 'fr',
  'Germany': 'de',
  'Spain': 'es',
  'Portugal': 'pt',
  'Netherlands': 'nl',
  'Belgium': 'be',
  'Italy': 'it',
  'Croatia': 'hr',
  'Uruguay': 'uy',
  'Colombia': 'co',
  'Japan': 'jp',
  'South Korea': 'kr',
  'Australia': 'au',
  'Saudi Arabia': 'sa',
  'Iran': 'ir',
  'Qatar': 'qa',
  'Canada': 'ca',
  'Morocco': 'ma',
  'Senegal': 'sn',
  'Ghana': 'gh',
  'Cameroon': 'cm',
  'Nigeria': 'ng',
  'Tunisia': 'tn',
  'Egypt': 'eg',
  'Algeria': 'dz',
  'Ecuador': 'ec',
  'Chile': 'cl',
  'Peru': 'pe',
  'Paraguay': 'py',
  'Bolivia': 'bo',
  'Venezuela': 've',
  'Costa Rica': 'cr',
  'Honduras': 'hn',
  'Panama': 'pa',
  'Jamaica': 'jm',
  'Trinidad and Tobago': 'tt',
  'Serbia': 'rs',
  'Switzerland': 'ch',
  'Denmark': 'dk',
  'Sweden': 'se',
  'Norway': 'no',
  'Poland': 'pl',
  'Ukraine': 'ua',
  'Czech Republic': 'cz',
  'Czechia': 'cz',
  'Austria': 'at',
  'Hungary': 'hu',
  'Romania': 'ro',
  'Greece': 'gr',
  'Turkey': 'tr',
  'Scotland': 'gb-sct',
  'Wales': 'gb-wls',
  'Ireland': 'ie',
  'Republic of Ireland': 'ie',
  'Northern Ireland': 'gb-nir',
  'Iceland': 'is',
  'Finland': 'fi',
  'Russia': 'ru',
  'China': 'cn',
  'India': 'in',
  'Indonesia': 'id',
  'Thailand': 'th',
  'Vietnam': 'vn',
  'New Zealand': 'nz',
  'Ivory Coast': 'ci',
  "Côte d'Ivoire": 'ci',
  'DR Congo': 'cd',
  'Mali': 'ml',
  'Burkina Faso': 'bf',
  'Zambia': 'zm',
  'Zimbabwe': 'zw',
  'Tanzania': 'tz',
  'Kenya': 'ke',
  'Uganda': 'ug',
  'Mozambique': 'mz',
  'Angola': 'ao',
  'Cabo Verde': 'cv',
  'Cape Verde': 'cv',
  'Guatemala': 'gt',
  'El Salvador': 'sv',
  'Cuba': 'cu',
  'Dominican Republic': 'do',
  'Haiti': 'ht',
  'Uzbekistan': 'uz',
  'Iraq': 'iq',
  'Syria': 'sy',
  'Jordan': 'jo',
  'Palestine': 'ps',
  'Oman': 'om',
  'UAE': 'ae',
  'United Arab Emirates': 'ae',
  'Bahrain': 'bh',
  'Kuwait': 'kw',
  'Malaysia': 'my',
  'Philippines': 'ph',
  'Singapore': 'sg',
  'Slovakia': 'sk',
  'Slovenia': 'si',
  'Bulgaria': 'bg',
  'Albania': 'al',
  'North Macedonia': 'mk',
  'Montenegro': 'me',
  'Bosnia and Herzegovina': 'ba',
  'Bosnia': 'ba',
  'Kosovo': 'xk',
  'Georgia': 'ge',
  'Armenia': 'am',
  'Azerbaijan': 'az',
  'Kazakhstan': 'kz',
  'Kyrgyzstan': 'kg',
  'Tajikistan': 'tj',
  'Turkmenistan': 'tm',
  'Afghanistan': 'af',
  'Pakistan': 'pk',
  'Bangladesh': 'bd',
  'Sri Lanka': 'lk',
  'Nepal': 'np',
  'Myanmar': 'mm',
  'Cambodia': 'kh',
  'Laos': 'la',
};

export function getFlag(teamName) {
  const code = teamCodes[teamName];
  if (!code) return null;
  return `https://flagcdn.com/24x18/${code}.png`;
}

export function getFlagCode(teamName) {
  return teamCodes[teamName] || null;
}

export default teamCodes;
