// FIFA 2026 World Cup Players Seed Data
// Based on latest squad selections (May 2026)

const players = [
  // ===== GROUP A: Mexico, South Africa, South Korea, Czechia =====
  // Mexico
  { name: 'Carlos Acevedo', team: 'Mexico', position: 'GK', shirt_number: 1 },
  { name: 'Raul Rangel', team: 'Mexico', position: 'GK', shirt_number: 12 },
  { name: 'Guillermo Ochoa', team: 'Mexico', position: 'GK', shirt_number: 13 },
  { name: 'Jesus Gallardo', team: 'Mexico', position: 'DEF', shirt_number: 3 },
  { name: 'Edson Alvarez', team: 'Mexico', position: 'DEF', shirt_number: 4 },
  { name: 'Cesar Montes', team: 'Mexico', position: 'DEF', shirt_number: 5 },
  { name: 'Johan Vasquez', team: 'Mexico', position: 'DEF', shirt_number: 6 },
  { name: 'Israel Reyes', team: 'Mexico', position: 'DEF', shirt_number: 2 },
  { name: 'Kevin Alvarez', team: 'Mexico', position: 'DEF', shirt_number: 15 },
  { name: 'Mateo Chavez', team: 'Mexico', position: 'DEF', shirt_number: 16 },
  { name: 'Orbelin Pineda', team: 'Mexico', position: 'MID', shirt_number: 8 },
  { name: 'Erick Sanchez', team: 'Mexico', position: 'MID', shirt_number: 10 },
  { name: 'Erik Lira', team: 'Mexico', position: 'MID', shirt_number: 14 },
  { name: 'Gilberto Mora', team: 'Mexico', position: 'MID', shirt_number: 17 },
  { name: 'Alexis Gutierrez', team: 'Mexico', position: 'MID', shirt_number: 18 },
  { name: 'Fidel Ambriz', team: 'Mexico', position: 'MID', shirt_number: 19 },
  { name: 'Obed Vargas', team: 'Mexico', position: 'MID', shirt_number: 20 },
  { name: 'Jorge Ruvalcaba', team: 'Mexico', position: 'MID', shirt_number: 21 },
  { name: 'Raul Jimenez', team: 'Mexico', position: 'FWD', shirt_number: 9 },
  { name: 'Hirving Lozano', team: 'Mexico', position: 'FWD', shirt_number: 11 },
  { name: 'Roberto Alvarado', team: 'Mexico', position: 'FWD', shirt_number: 7 },
  { name: 'Diego Lainez', team: 'Mexico', position: 'FWD', shirt_number: 22 },
  { name: 'German Berterame', team: 'Mexico', position: 'FWD', shirt_number: 23 },
  { name: 'Armando Gonzalez', team: 'Mexico', position: 'FWD', shirt_number: 24 },

  // South Africa
  { name: 'Ronwen Williams', team: 'South Africa', position: 'GK', shirt_number: 1 },
  { name: 'Ricardo Goss', team: 'South Africa', position: 'GK', shirt_number: 16 },
  { name: 'Sipho Chaine', team: 'South Africa', position: 'GK', shirt_number: 23 },
  { name: 'Aubrey Modiba', team: 'South Africa', position: 'DEF', shirt_number: 3 },
  { name: 'Thapelo Morena', team: 'South Africa', position: 'DEF', shirt_number: 2 },
  { name: 'Khuliso Mudau', team: 'South Africa', position: 'DEF', shirt_number: 4 },
  { name: 'Nkosinathi Sibisi', team: 'South Africa', position: 'DEF', shirt_number: 5 },
  { name: 'Siyabonga Ngezana', team: 'South Africa', position: 'DEF', shirt_number: 6 },
  { name: 'Ime Okon', team: 'South Africa', position: 'DEF', shirt_number: 13 },
  { name: 'Mbekezeli Mbokazi', team: 'South Africa', position: 'DEF', shirt_number: 14 },
  { name: 'Fawaaz Basadien', team: 'South Africa', position: 'DEF', shirt_number: 15 },
  { name: 'Tylon Smith', team: 'South Africa', position: 'DEF', shirt_number: 22 },
  { name: 'Themba Zwane', team: 'South Africa', position: 'MID', shirt_number: 10 },
  { name: 'Teboho Mokoena', team: 'South Africa', position: 'MID', shirt_number: 8 },
  { name: 'Sphephelo Sithole', team: 'South Africa', position: 'MID', shirt_number: 17 },
  { name: 'Bathusi Aubaas', team: 'South Africa', position: 'MID', shirt_number: 18 },
  { name: 'Thalente Mbatha', team: 'South Africa', position: 'MID', shirt_number: 19 },
  { name: 'Luke Le Roux', team: 'South Africa', position: 'MID', shirt_number: 20 },
  { name: 'Patrick Maswanganyi', team: 'South Africa', position: 'MID', shirt_number: 21 },
  { name: 'Mduduzi Shabalala', team: 'South Africa', position: 'MID', shirt_number: 24 },
  { name: 'Evidence Makgopa', team: 'South Africa', position: 'FWD', shirt_number: 9 },
  { name: 'Lyle Foster', team: 'South Africa', position: 'FWD', shirt_number: 11 },
  { name: 'Oswin Appollis', team: 'South Africa', position: 'FWD', shirt_number: 7 },
  { name: 'Bongokuhle Hlongwane', team: 'South Africa', position: 'FWD', shirt_number: 12 },
  { name: 'Iqraam Rayners', team: 'South Africa', position: 'FWD', shirt_number: 25 },
  { name: 'Elias Mokwana', team: 'South Africa', position: 'FWD', shirt_number: 26 },
  { name: 'Relebohile Mofokeng', team: 'South Africa', position: 'FWD', shirt_number: 27 },

  // South Korea
  { name: 'Kim Seung-gyu', team: 'South Korea', position: 'GK', shirt_number: 1 },
  { name: 'Song Bum-keun', team: 'South Korea', position: 'GK', shirt_number: 12 },
  { name: 'Jo Hyeon-woo', team: 'South Korea', position: 'GK', shirt_number: 23 },
  { name: 'Kim Min-jae', team: 'South Korea', position: 'DEF', shirt_number: 4 },
  { name: 'Lee Myung-jae', team: 'South Korea', position: 'DEF', shirt_number: 2 },
  { name: 'Lee Han-beom', team: 'South Korea', position: 'DEF', shirt_number: 3 },
  { name: 'Lee Tae-seok', team: 'South Korea', position: 'DEF', shirt_number: 5 },
  { name: 'Cho Yu-min', team: 'South Korea', position: 'DEF', shirt_number: 6 },
  { name: 'Kim Moon-hwan', team: 'South Korea', position: 'DEF', shirt_number: 13 },
  { name: 'Park Jin-seob', team: 'South Korea', position: 'DEF', shirt_number: 14 },
  { name: 'Seol Young-woo', team: 'South Korea', position: 'DEF', shirt_number: 15 },
  { name: 'Kim Tae-hyeon', team: 'South Korea', position: 'DEF', shirt_number: 16 },
  { name: 'Won Du-jae', team: 'South Korea', position: 'MID', shirt_number: 8 },
  { name: 'Lee Jae-sung', team: 'South Korea', position: 'MID', shirt_number: 17 },
  { name: 'Hwang Hee-chan', team: 'South Korea', position: 'MID', shirt_number: 11 },
  { name: 'Lee Kang-in', team: 'South Korea', position: 'MID', shirt_number: 10 },
  { name: 'Bae Jun-ho', team: 'South Korea', position: 'MID', shirt_number: 18 },
  { name: 'Eom Ji-sung', team: 'South Korea', position: 'MID', shirt_number: 19 },
  { name: 'Seo Min-woo', team: 'South Korea', position: 'MID', shirt_number: 20 },
  { name: 'Kwon Hyeok-kyu', team: 'South Korea', position: 'MID', shirt_number: 21 },
  { name: 'Yang Min-hyeok', team: 'South Korea', position: 'MID', shirt_number: 22 },
  { name: 'Jens Castrop', team: 'South Korea', position: 'MID', shirt_number: 24 },
  { name: 'Kim Jin-gyu', team: 'South Korea', position: 'MID', shirt_number: 25 },
  { name: 'Son Heung-min', team: 'South Korea', position: 'FWD', shirt_number: 7 },
  { name: 'Cho Gue-sung', team: 'South Korea', position: 'FWD', shirt_number: 9 },
  { name: 'Oh Hyeon-gyu', team: 'South Korea', position: 'FWD', shirt_number: 26 },

  // Czechia (placeholder squad - to be announced)
  { name: 'Jindrich Stanek', team: 'Czechia', position: 'GK', shirt_number: 1 },
  { name: 'Vitezslav Jaros', team: 'Czechia', position: 'GK', shirt_number: 23 },
  { name: 'Ladislav Krejci', team: 'Czechia', position: 'DEF', shirt_number: 3 },
  { name: 'Robin Hranac', team: 'Czechia', position: 'DEF', shirt_number: 4 },
  { name: 'Vladimir Coufal', team: 'Czechia', position: 'DEF', shirt_number: 5 },
  { name: 'David Zima', team: 'Czechia', position: 'DEF', shirt_number: 6 },
  { name: 'Tomas Holes', team: 'Czechia', position: 'MID', shirt_number: 8 },
  { name: 'Lukas Provod', team: 'Czechia', position: 'MID', shirt_number: 10 },
  { name: 'Adam Hlozek', team: 'Czechia', position: 'FWD', shirt_number: 9 },
  { name: 'Patrik Schick', team: 'Czechia', position: 'FWD', shirt_number: 11 },
  { name: 'Mojmir Chytil', team: 'Czechia', position: 'FWD', shirt_number: 7 },

  // ===== GROUP B: Canada, Bosnia & Herzegovina, Qatar, Switzerland =====
  // Canada
  { name: 'Dayne St. Clair', team: 'Canada', position: 'GK', shirt_number: 1 },
  { name: 'Maxime Crepeau', team: 'Canada', position: 'GK', shirt_number: 16 },
  { name: 'Zorhan Bassong', team: 'Canada', position: 'DEF', shirt_number: 2 },
  { name: 'Kamal Miller', team: 'Canada', position: 'DEF', shirt_number: 3 },
  { name: 'Joel Waterman', team: 'Canada', position: 'DEF', shirt_number: 4 },
  { name: 'Derek Cornelius', team: 'Canada', position: 'DEF', shirt_number: 5 },
  { name: 'Richie Laryea', team: 'Canada', position: 'DEF', shirt_number: 22 },
  { name: 'Stephen Eustaquio', team: 'Canada', position: 'MID', shirt_number: 7 },
  { name: 'Ismael Kone', team: 'Canada', position: 'MID', shirt_number: 8 },
  { name: 'Tajon Buchanan', team: 'Canada', position: 'MID', shirt_number: 11 },
  { name: 'Jonathan Osorio', team: 'Canada', position: 'MID', shirt_number: 21 },
  { name: 'Ali Ahmed', team: 'Canada', position: 'MID', shirt_number: 14 },
  { name: 'Cyle Larin', team: 'Canada', position: 'FWD', shirt_number: 17 },
  { name: 'Jonathan David', team: 'Canada', position: 'FWD', shirt_number: 9 },
  { name: 'Tani Oluwaseyi', team: 'Canada', position: 'FWD', shirt_number: 19 },

  // Switzerland
  { name: 'Gregor Kobel', team: 'Switzerland', position: 'GK', shirt_number: 1 },
  { name: 'Yvon Mvogo', team: 'Switzerland', position: 'GK', shirt_number: 12 },
  { name: 'Manuel Akanji', team: 'Switzerland', position: 'DEF', shirt_number: 5 },
  { name: 'Nico Elvedi', team: 'Switzerland', position: 'DEF', shirt_number: 4 },
  { name: 'Ricardo Rodriguez', team: 'Switzerland', position: 'DEF', shirt_number: 3 },
  { name: 'Silvan Widmer', team: 'Switzerland', position: 'DEF', shirt_number: 2 },
  { name: 'Aurele Amenda', team: 'Switzerland', position: 'DEF', shirt_number: 6 },
  { name: 'Granit Xhaka', team: 'Switzerland', position: 'MID', shirt_number: 10 },
  { name: 'Djibril Sow', team: 'Switzerland', position: 'MID', shirt_number: 8 },
  { name: 'Fabian Rieder', team: 'Switzerland', position: 'MID', shirt_number: 14 },
  { name: 'Michel Aebischer', team: 'Switzerland', position: 'MID', shirt_number: 15 },
  { name: 'Breel Embolo', team: 'Switzerland', position: 'FWD', shirt_number: 9 },
  { name: 'Dan Ndoye', team: 'Switzerland', position: 'FWD', shirt_number: 11 },
  { name: 'Ruben Vargas', team: 'Switzerland', position: 'FWD', shirt_number: 7 },

  // Qatar
  { name: 'Meshaal Barsham', team: 'Qatar', position: 'GK', shirt_number: 1 },
  { name: 'Shehab Ellethy', team: 'Qatar', position: 'GK', shirt_number: 21 },
  { name: 'Tarek Salman', team: 'Qatar', position: 'DEF', shirt_number: 3 },
  { name: 'Homam Ahmed', team: 'Qatar', position: 'DEF', shirt_number: 4 },
  { name: 'Sultan Al-Brake', team: 'Qatar', position: 'DEF', shirt_number: 5 },
  { name: 'Lucas Mendes', team: 'Qatar', position: 'DEF', shirt_number: 2 },
  { name: 'Abdulaziz Hatem', team: 'Qatar', position: 'MID', shirt_number: 8 },
  { name: 'Mohammed Waad', team: 'Qatar', position: 'MID', shirt_number: 6 },
  { name: 'Assim Madibo', team: 'Qatar', position: 'MID', shirt_number: 14 },
  { name: 'Akram Afif', team: 'Qatar', position: 'FWD', shirt_number: 11 },
  { name: 'Mohammed Muntari', team: 'Qatar', position: 'FWD', shirt_number: 9 },
  { name: 'Edmilson Junior', team: 'Qatar', position: 'FWD', shirt_number: 7 },
  { name: 'Ahmed Alaaeldin', team: 'Qatar', position: 'FWD', shirt_number: 10 },

