const { pool } = require('./database');

// Projected squads for all 48 FIFA 2026 World Cup teams
// Based on current top players as of May 2026
// Each team has 26 players (GK x3, DEF x8, MID x8, FWD x7)

const squads = {
  'Mexico': [
    { name: 'Raul Rangel', position: 'GK', shirt_number: 1 },
    { name: 'Guillermo Ochoa', position: 'GK', shirt_number: 13 },
    { name: 'Carlos Acevedo', position: 'GK', shirt_number: 23 },
    { name: 'Jorge Sanchez', position: 'DEF', shirt_number: 2 },
    { name: 'Cesar Montes', position: 'DEF', shirt_number: 3 },
    { name: 'Edson Alvarez', position: 'DEF', shirt_number: 4 },
    { name: 'Johan Vasquez', position: 'DEF', shirt_number: 5 },
    { name: 'Gerardo Arteaga', position: 'DEF', shirt_number: 6 },
    { name: 'Kevin Alvarez', position: 'DEF', shirt_number: 15 },
    { name: 'Jesus Gallardo', position: 'DEF', shirt_number: 19 },
    { name: 'Israel Reyes', position: 'DEF', shirt_number: 22 },
    { name: 'Luis Romo', position: 'MID', shirt_number: 7 },
    { name: 'Carlos Rodriguez', position: 'MID', shirt_number: 8 },
    { name: 'Orbelin Pineda', position: 'MID', shirt_number: 10 },
    { name: 'Luis Chavez', position: 'MID', shirt_number: 14 },
    { name: 'Erick Sanchez', position: 'MID', shirt_number: 16 },
    { name: 'Diego Lainez', position: 'MID', shirt_number: 17 },
    { name: 'Marcel Ruiz', position: 'MID', shirt_number: 18 },
    { name: 'Roberto Alvarado', position: 'MID', shirt_number: 20 },
    { name: 'Hirving Lozano', position: 'FWD', shirt_number: 9 },
    { name: 'Santiago Gimenez', position: 'FWD', shirt_number: 11 },
    { name: 'Alexis Vega', position: 'FWD', shirt_number: 12 },
    { name: 'Uriel Antuna', position: 'FWD', shirt_number: 21 },
    { name: 'Henry Martin', position: 'FWD', shirt_number: 24 },
    { name: 'Julian Quinones', position: 'FWD', shirt_number: 25 },
    { name: 'Guillermo Martinez', position: 'FWD', shirt_number: 26 },
  ],
  'South Africa': [
    { name: 'Ronwen Williams', position: 'GK', shirt_number: 1 },
    { name: 'Veli Mothwa', position: 'GK', shirt_number: 16 },
    { name: 'Bruce Bvuma', position: 'GK', shirt_number: 23 },
    { name: 'Siyanda Xulu', position: 'DEF', shirt_number: 2 },
    { name: 'Mothobi Mvala', position: 'DEF', shirt_number: 3 },
    { name: 'Thibang Phete', position: 'DEF', shirt_number: 4 },
    { name: 'Aubrey Modiba', position: 'DEF', shirt_number: 5 },
    { name: 'Rushwin Dortley', position: 'DEF', shirt_number: 6 },
    { name: 'Grant Kekana', position: 'DEF', shirt_number: 13 },
    { name: 'Khuliso Mudau', position: 'DEF', shirt_number: 15 },
    { name: 'Nkosinathi Sibisi', position: 'DEF', shirt_number: 22 },
    { name: 'Themba Zwane', position: 'MID', shirt_number: 7 },
    { name: 'Teboho Mokoena', position: 'MID', shirt_number: 8 },
    { name: 'Bathusi Aubaas', position: 'MID', shirt_number: 10 },
    { name: 'Luke Le Roux', position: 'MID', shirt_number: 14 },
    { name: 'Ethan Brooks', position: 'MID', shirt_number: 17 },
    { name: 'Patrick Maswanganyi', position: 'MID', shirt_number: 18 },
    { name: 'Sipho Mbule', position: 'MID', shirt_number: 19 },
    { name: 'Oswin Appollis', position: 'MID', shirt_number: 20 },
    { name: 'Percy Tau', position: 'FWD', shirt_number: 9 },
    { name: 'Lyle Foster', position: 'FWD', shirt_number: 11 },
    { name: 'Iqraam Rayners', position: 'FWD', shirt_number: 12 },
    { name: 'Evidence Makgopa', position: 'FWD', shirt_number: 21 },
    { name: 'Elias Mokwana', position: 'FWD', shirt_number: 24 },
    { name: 'Relebohile Mofokeng', position: 'FWD', shirt_number: 25 },
    { name: 'Thapelo Morena', position: 'FWD', shirt_number: 26 },
  ],
  'South Korea': [
    { name: 'Kim Seung-gyu', position: 'GK', shirt_number: 1 },
    { name: 'Jo Hyeon-woo', position: 'GK', shirt_number: 21 },
    { name: 'Song Bum-keun', position: 'GK', shirt_number: 23 },
    { name: 'Kim Min-jae', position: 'DEF', shirt_number: 3 },
    { name: 'Kim Jin-su', position: 'DEF', shirt_number: 4 },
    { name: 'Jung Seung-hyun', position: 'DEF', shirt_number: 5 },
    { name: 'Park Ji-su', position: 'DEF', shirt_number: 6 },
    { name: 'Kim Tae-hwan', position: 'DEF', shirt_number: 2 },
    { name: 'Cho Yu-min', position: 'DEF', shirt_number: 15 },
    { name: 'Hong Chul', position: 'DEF', shirt_number: 14 },
    { name: 'Seol Young-woo', position: 'DEF', shirt_number: 22 },
    { name: 'Son Heung-min', position: 'FWD', shirt_number: 7 },
    { name: 'Hwang Hee-chan', position: 'FWD', shirt_number: 11 },
    { name: 'Lee Kang-in', position: 'MID', shirt_number: 10 },
    { name: 'Jung Woo-young', position: 'MID', shirt_number: 8 },
    { name: 'Hwang In-beom', position: 'MID', shirt_number: 16 },
    { name: 'Lee Jae-sung', position: 'MID', shirt_number: 17 },
    { name: 'Paik Seung-ho', position: 'MID', shirt_number: 18 },
    { name: 'Kwon Chang-hoon', position: 'MID', shirt_number: 19 },
    { name: 'Park Yong-woo', position: 'MID', shirt_number: 20 },
    { name: 'Yang Hyun-jun', position: 'MID', shirt_number: 13 },
    { name: 'Cho Gue-sung', position: 'FWD', shirt_number: 9 },
    { name: 'Oh Hyeon-gyu', position: 'FWD', shirt_number: 12 },
    { name: 'Joo Min-kyu', position: 'FWD', shirt_number: 24 },
    { name: 'Lee Young-jun', position: 'FWD', shirt_number: 25 },
    { name: 'Song Min-kyu', position: 'FWD', shirt_number: 26 },
  ],
  'Czechia': [
    { name: 'Jindrich Stanek', position: 'GK', shirt_number: 1 },
    { name: 'Vitezslav Jaros', position: 'GK', shirt_number: 16 },
    { name: 'Matej Kovar', position: 'GK', shirt_number: 23 },
    { name: 'Vladimir Coufal', position: 'DEF', shirt_number: 2 },
    { name: 'Tomas Holes', position: 'DEF', shirt_number: 3 },
    { name: 'Robin Hranac', position: 'DEF', shirt_number: 4 },
    { name: 'Ladislav Krejci', position: 'DEF', shirt_number: 5 },
    { name: 'David Zima', position: 'DEF', shirt_number: 6 },
    { name: 'Martin Vitik', position: 'DEF', shirt_number: 15 },
    { name: 'Tomas Vlcek', position: 'DEF', shirt_number: 22 },
    { name: 'Matej Jurasek', position: 'DEF', shirt_number: 13 },
    { name: 'Tomas Soucek', position: 'MID', shirt_number: 8 },
    { name: 'Alex Kral', position: 'MID', shirt_number: 7 },
    { name: 'Lukas Provod', position: 'MID', shirt_number: 10 },
    { name: 'Vaclav Cerny', position: 'MID', shirt_number: 14 },
    { name: 'Michal Sadilek', position: 'MID', shirt_number: 17 },
    { name: 'Pavel Sulc', position: 'MID', shirt_number: 18 },
    { name: 'Ondrej Lingr', position: 'MID', shirt_number: 19 },
    { name: 'David Doudera', position: 'MID', shirt_number: 20 },
    { name: 'Patrik Schick', position: 'FWD', shirt_number: 9 },
    { name: 'Adam Hlozek', position: 'FWD', shirt_number: 11 },
    { name: 'Mojmir Chytil', position: 'FWD', shirt_number: 12 },
    { name: 'Jan Kuchta', position: 'FWD', shirt_number: 21 },
    { name: 'Tomas Chory', position: 'FWD', shirt_number: 24 },
    { name: 'Daniel Vasulin', position: 'FWD', shirt_number: 25 },
    { name: 'Matej Jurasek', position: 'FWD', shirt_number: 26 },
  ],
  'Canada': [
    { name: 'Maxime Crepeau', position: 'GK', shirt_number: 1 },
    { name: 'Dayne St. Clair', position: 'GK', shirt_number: 16 },
    { name: 'James Pantemis', position: 'GK', shirt_number: 23 },
    { name: 'Alistair Johnston', position: 'DEF', shirt_number: 2 },
    { name: 'Sam Adekugbe', position: 'DEF', shirt_number: 3 },
    { name: 'Moise Bombito', position: 'DEF', shirt_number: 4 },
    { name: 'Steven Vitoria', position: 'DEF', shirt_number: 5 },
    { name: 'Kamal Miller', position: 'DEF', shirt_number: 6 },
    { name: 'Derek Cornelius', position: 'DEF', shirt_number: 15 },
    { name: 'Richie Laryea', position: 'DEF', shirt_number: 22 },
    { name: 'Luca Koleosho', position: 'DEF', shirt_number: 13 },
    { name: 'Alphonso Davies', position: 'MID', shirt_number: 19 },
    { name: 'Stephen Eustaquio', position: 'MID', shirt_number: 7 },
    { name: 'Ismael Kone', position: 'MID', shirt_number: 8 },
    { name: 'Mark-Anthony Kaye', position: 'MID', shirt_number: 14 },
    { name: 'Samuel Piette', position: 'MID', shirt_number: 17 },
    { name: 'Liam Millar', position: 'MID', shirt_number: 18 },
    { name: 'Ali Ahmed', position: 'MID', shirt_number: 20 },
    { name: 'Mathieu Choiniere', position: 'MID', shirt_number: 21 },
    { name: 'Jonathan David', position: 'FWD', shirt_number: 9 },
    { name: 'Junior Hoilett', position: 'FWD', shirt_number: 10 },
    { name: 'Tajon Buchanan', position: 'FWD', shirt_number: 11 },
    { name: 'Cyle Larin', position: 'FWD', shirt_number: 12 },
    { name: 'Tani Oluwaseyi', position: 'FWD', shirt_number: 24 },
    { name: 'Jacen Russell-Rowe', position: 'FWD', shirt_number: 25 },
    { name: 'Jonathan Osorio', position: 'FWD', shirt_number: 26 },
  ],
  'Switzerland': [
    { name: 'Yann Sommer', position: 'GK', shirt_number: 1 },
    { name: 'Gregor Kobel', position: 'GK', shirt_number: 12 },
    { name: 'Yvon Mvogo', position: 'GK', shirt_number: 23 },
    { name: 'Silvan Widmer', position: 'DEF', shirt_number: 2 },
    { name: 'Manuel Akanji', position: 'DEF', shirt_number: 3 },
    { name: 'Nico Elvedi', position: 'DEF', shirt_number: 4 },
    { name: 'Ricardo Rodriguez', position: 'DEF', shirt_number: 5 },
    { name: 'Leonidas Stergiou', position: 'DEF', shirt_number: 6 },
    { name: 'Eray Comert', position: 'DEF', shirt_number: 15 },
    { name: 'Cedric Zesiger', position: 'DEF', shirt_number: 22 },
    { name: 'Ulisses Garcia', position: 'DEF', shirt_number: 13 },
    { name: 'Granit Xhaka', position: 'MID', shirt_number: 10 },
    { name: 'Remo Freuler', position: 'MID', shirt_number: 8 },
    { name: 'Denis Zakaria', position: 'MID', shirt_number: 7 },
    { name: 'Xherdan Shaqiri', position: 'MID', shirt_number: 14 },
    { name: 'Fabian Rieder', position: 'MID', shirt_number: 16 },
    { name: 'Ardon Jashari', position: 'MID', shirt_number: 17 },
    { name: 'Vincent Sierro', position: 'MID', shirt_number: 18 },
    { name: 'Michel Aebischer', position: 'MID', shirt_number: 20 },
    { name: 'Breel Embolo', position: 'FWD', shirt_number: 9 },
    { name: 'Noah Okafor', position: 'FWD', shirt_number: 11 },
    { name: 'Dan Ndoye', position: 'FWD', shirt_number: 19 },
    { name: 'Zeki Amdouni', position: 'FWD', shirt_number: 21 },
    { name: 'Ruben Vargas', position: 'FWD', shirt_number: 24 },
    { name: 'Joel Monteiro', position: 'FWD', shirt_number: 25 },
    { name: 'Andi Zeqiri', position: 'FWD', shirt_number: 26 },
  ],
  'Qatar': [
    { name: 'Saad Al Sheeb', position: 'GK', shirt_number: 1 },
    { name: 'Meshaal Barsham', position: 'GK', shirt_number: 21 },
    { name: 'Yousuf Hassan', position: 'GK', shirt_number: 23 },
    { name: 'Pedro Miguel', position: 'DEF', shirt_number: 2 },
    { name: 'Abdelkarim Hassan', position: 'DEF', shirt_number: 3 },
    { name: 'Bassam Al-Rawi', position: 'DEF', shirt_number: 4 },
    { name: 'Tarek Salman', position: 'DEF', shirt_number: 5 },
    { name: 'Musab Kheder', position: 'DEF', shirt_number: 6 },
    { name: 'Homam Ahmed', position: 'DEF', shirt_number: 15 },
    { name: 'Boualem Khoukhi', position: 'DEF', shirt_number: 16 },
    { name: 'Jassem Gaber', position: 'DEF', shirt_number: 22 },
    { name: 'Karim Boudiaf', position: 'MID', shirt_number: 7 },
    { name: 'Ali Assadalla', position: 'MID', shirt_number: 8 },
    { name: 'Hassan Al-Haydos', position: 'MID', shirt_number: 10 },
    { name: 'Abdulaziz Hatem', position: 'MID', shirt_number: 14 },
    { name: 'Assim Madibo', position: 'MID', shirt_number: 17 },
    { name: 'Mohammed Waad', position: 'MID', shirt_number: 18 },
    { name: 'Ahmed Fatehi', position: 'MID', shirt_number: 19 },
    { name: 'Salem Al-Hajri', position: 'MID', shirt_number: 20 },
    { name: 'Almoez Ali', position: 'FWD', shirt_number: 9 },
    { name: 'Akram Afif', position: 'FWD', shirt_number: 11 },
    { name: 'Mohammed Muntari', position: 'FWD', shirt_number: 12 },
    { name: 'Ahmed Alaaeldin', position: 'FWD', shirt_number: 13 },
    { name: 'Yusuf Abdurisag', position: 'FWD', shirt_number: 24 },
    { name: 'Mubarak Almuwallad', position: 'FWD', shirt_number: 25 },
    { name: 'Hashim Ali', position: 'FWD', shirt_number: 26 },
  ],
  'Bosnia and Herzegovina': [
    { name: 'Nikola Vasilj', position: 'GK', shirt_number: 1 },
    { name: 'Kenan Piric', position: 'GK', shirt_number: 12 },
    { name: 'Vladan Kovacevic', position: 'GK', shirt_number: 23 },
    { name: 'Sead Kolasinac', position: 'DEF', shirt_number: 3 },
    { name: 'Amir Hadziahmetovic', position: 'DEF', shirt_number: 4 },
    { name: 'Sasa Kalajdzic', position: 'DEF', shirt_number: 5 },
    { name: 'Dennis Hadzikadunic', position: 'DEF', shirt_number: 6 },
    { name: 'Anel Ahmedhodzic', position: 'DEF', shirt_number: 2 },
    { name: 'Ermin Bicakcic', position: 'DEF', shirt_number: 15 },
    { name: 'Amar Dedic', position: 'DEF', shirt_number: 22 },
    { name: 'Nikola Katic', position: 'DEF', shirt_number: 13 },
    { name: 'Miralem Pjanic', position: 'MID', shirt_number: 8 },
    { name: 'Amer Gojak', position: 'MID', shirt_number: 7 },
    { name: 'Haris Hajradinovic', position: 'MID', shirt_number: 10 },
    { name: 'Armin Gigovic', position: 'MID', shirt_number: 14 },
    { name: 'Ivan Basic', position: 'MID', shirt_number: 16 },
    { name: 'Benjamin Tahirovic', position: 'MID', shirt_number: 17 },
    { name: 'Rade Krunic', position: 'MID', shirt_number: 18 },
    { name: 'Smail Prevljak', position: 'MID', shirt_number: 20 },
    { name: 'Edin Dzeko', position: 'FWD', shirt_number: 9 },
    { name: 'Haris Tabakovic', position: 'FWD', shirt_number: 11 },
    { name: 'Ermedin Demirovic', position: 'FWD', shirt_number: 19 },
    { name: 'Luka Menalo', position: 'FWD', shirt_number: 21 },
    { name: 'Denis Huseinbasic', position: 'FWD', shirt_number: 24 },
    { name: 'Kenan Kodro', position: 'FWD', shirt_number: 25 },
    { name: 'Deni Juric', position: 'FWD', shirt_number: 26 },
  ],
  'Brazil': [
    { name: 'Alisson Becker', position: 'GK', shirt_number: 1 },
    { name: 'Ederson Moraes', position: 'GK', shirt_number: 12 },
    { name: 'Bento', position: 'GK', shirt_number: 23 },
    { name: 'Danilo', position: 'DEF', shirt_number: 2 },
    { name: 'Marquinhos', position: 'DEF', shirt_number: 3 },
    { name: 'Gabriel Magalhaes', position: 'DEF', shirt_number: 4 },
    { name: 'Militao', position: 'DEF', shirt_number: 5 },
    { name: 'Alex Sandro', position: 'DEF', shirt_number: 6 },
    { name: 'Beraldo', position: 'DEF', shirt_number: 13 },
    { name: 'Wendell', position: 'DEF', shirt_number: 15 },
    { name: 'Yan Couto', position: 'DEF', shirt_number: 22 },
    { name: 'Lucas Paqueta', position: 'MID', shirt_number: 7 },
    { name: 'Bruno Guimaraes', position: 'MID', shirt_number: 8 },
    { name: 'Casemiro', position: 'MID', shirt_number: 10 },
    { name: 'Joao Gomes', position: 'MID', shirt_number: 14 },
    { name: 'Andre', position: 'MID', shirt_number: 16 },
    { name: 'Andreas Pereira', position: 'MID', shirt_number: 17 },
    { name: 'Gerson', position: 'MID', shirt_number: 18 },
    { name: 'Raphinha', position: 'MID', shirt_number: 19 },
    { name: 'Vinicius Junior', position: 'FWD', shirt_number: 9 },
    { name: 'Rodrygo', position: 'FWD', shirt_number: 11 },
    { name: 'Endrick', position: 'FWD', shirt_number: 20 },
    { name: 'Savinho', position: 'FWD', shirt_number: 21 },
    { name: 'Gabriel Martinelli', position: 'FWD', shirt_number: 24 },
    { name: 'Estevao', position: 'FWD', shirt_number: 25 },
    { name: 'Igor Jesus', position: 'FWD', shirt_number: 26 },
  ],
  'Morocco': [
    { name: 'Yassine Bounou', position: 'GK', shirt_number: 1 },
    { name: 'Munir El Kajoui', position: 'GK', shirt_number: 12 },
    { name: 'Anas Zniti', position: 'GK', shirt_number: 23 },
    { name: 'Achraf Hakimi', position: 'DEF', shirt_number: 2 },
    { name: 'Noussair Mazraoui', position: 'DEF', shirt_number: 3 },
    { name: 'Nayef Aguerd', position: 'DEF', shirt_number: 4 },
    { name: 'Romain Saiss', position: 'DEF', shirt_number: 5 },
    { name: 'Adam Aznou', position: 'DEF', shirt_number: 6 },
    { name: 'Badr Benoun', position: 'DEF', shirt_number: 13 },
    { name: 'Jawad El Yamiq', position: 'DEF', shirt_number: 15 },
    { name: 'Achraf Dari', position: 'DEF', shirt_number: 22 },
    { name: 'Hakim Ziyech', position: 'MID', shirt_number: 7 },
    { name: 'Azzedine Ounahi', position: 'MID', shirt_number: 8 },
    { name: 'Sofyan Amrabat', position: 'MID', shirt_number: 10 },
    { name: 'Bilal El Khannouss', position: 'MID', shirt_number: 14 },
    { name: 'Selim Amallah', position: 'MID', shirt_number: 16 },
    { name: 'Ibrahim Diaz', position: 'MID', shirt_number: 17 },
    { name: 'Abde Ezzalzouli', position: 'MID', shirt_number: 18 },
    { name: 'Ilias Akhomach', position: 'MID', shirt_number: 19 },
    { name: 'Youssef En-Nesyri', position: 'FWD', shirt_number: 9 },
    { name: 'Ayoub El Kaabi', position: 'FWD', shirt_number: 11 },
    { name: 'Sofiane Rahimi', position: 'FWD', shirt_number: 20 },
    { name: 'Hamza Igamane', position: 'FWD', shirt_number: 21 },
    { name: 'Amine Harit', position: 'FWD', shirt_number: 24 },
    { name: 'Eliesse Ben Seghir', position: 'FWD', shirt_number: 25 },
    { name: 'Soufiane Rahimi', position: 'FWD', shirt_number: 26 },
  ],
  'Haiti': [
    { name: 'Alexandre Balde', position: 'GK', shirt_number: 1 },
    { name: 'Josue Duverger', position: 'GK', shirt_number: 16 },
    { name: 'Lamy Etienne', position: 'GK', shirt_number: 23 },
    { name: 'Carlens Arcus', position: 'DEF', shirt_number: 2 },
    { name: 'Ricardo Ade', position: 'DEF', shirt_number: 3 },
    { name: 'Jems Geffrard', position: 'DEF', shirt_number: 4 },
    { name: 'Alex Junior', position: 'DEF', shirt_number: 5 },
    { name: 'Stephane Lambese', position: 'DEF', shirt_number: 6 },
    { name: 'Josue Destine', position: 'DEF', shirt_number: 13 },
    { name: 'Zachary Herivaux', position: 'DEF', shirt_number: 15 },
    { name: 'Mikaelson Jeannis', position: 'DEF', shirt_number: 22 },
    { name: 'Derrick Etienne Jr', position: 'MID', shirt_number: 7 },
    { name: 'Melchie Dumornay', position: 'MID', shirt_number: 8 },
    { name: 'Steeven Saba', position: 'MID', shirt_number: 10 },
    { name: 'Bryan Alceus', position: 'MID', shirt_number: 14 },
    { name: 'Leverton Pierre', position: 'MID', shirt_number: 17 },
    { name: 'Christiano Francois', position: 'MID', shirt_number: 18 },
    { name: 'Obed Vargas', position: 'MID', shirt_number: 19 },
    { name: 'Danley Jean Jacques', position: 'MID', shirt_number: 20 },
    { name: 'Frantzdy Pierrot', position: 'FWD', shirt_number: 9 },
    { name: 'Duckens Nazon', position: 'FWD', shirt_number: 11 },
    { name: 'Carnejy Antoine', position: 'FWD', shirt_number: 12 },
    { name: 'Ronaldo Damus', position: 'FWD', shirt_number: 21 },
    { name: 'Geoffrey Chery', position: 'FWD', shirt_number: 24 },
    { name: 'Ricardo Ade Jr', position: 'FWD', shirt_number: 25 },
    { name: 'Kervens Jolicoeur', position: 'FWD', shirt_number: 26 },
  ],
  'Scotland': [
    { name: 'Angus Gunn', position: 'GK', shirt_number: 1 },
    { name: 'Craig Gordon', position: 'GK', shirt_number: 12 },
    { name: 'Zander Clark', position: 'GK', shirt_number: 23 },
    { name: 'Anthony Ralston', position: 'DEF', shirt_number: 2 },
    { name: 'Andrew Robertson', position: 'DEF', shirt_number: 3 },
    { name: 'Scott McKenna', position: 'DEF', shirt_number: 4 },
    { name: 'Grant Hanley', position: 'DEF', shirt_number: 5 },
    { name: 'Kieran Tierney', position: 'DEF', shirt_number: 6 },
    { name: 'Jack Hendry', position: 'DEF', shirt_number: 13 },
    { name: 'Liam Lindsay', position: 'DEF', shirt_number: 15 },
    { name: 'Greg Taylor', position: 'DEF', shirt_number: 22 },
    { name: 'John McGinn', position: 'MID', shirt_number: 7 },
    { name: 'Callum McGregor', position: 'MID', shirt_number: 8 },
    { name: 'Scott McTominay', position: 'MID', shirt_number: 10 },
    { name: 'Billy Gilmour', position: 'MID', shirt_number: 14 },
    { name: 'Kenny McLean', position: 'MID', shirt_number: 16 },
    { name: 'Stuart Armstrong', position: 'MID', shirt_number: 17 },
    { name: 'Lewis Morgan', position: 'MID', shirt_number: 18 },
    { name: 'Ryan Christie', position: 'MID', shirt_number: 19 },
    { name: 'Lyndon Dykes', position: 'FWD', shirt_number: 9 },
    { name: 'Che Adams', position: 'FWD', shirt_number: 11 },
    { name: 'Lawrence Shankland', position: 'FWD', shirt_number: 20 },
    { name: 'Ben Doak', position: 'FWD', shirt_number: 21 },
    { name: 'Tommy Conway', position: 'FWD', shirt_number: 24 },
    { name: 'Kevin Nisbet', position: 'FWD', shirt_number: 25 },
    { name: 'Ross Stewart', position: 'FWD', shirt_number: 26 },
  ],
  'USA': [
    { name: 'Matt Turner', position: 'GK', shirt_number: 1 },
    { name: 'Ethan Horvath', position: 'GK', shirt_number: 12 },
    { name: 'Patrick Schulte', position: 'GK', shirt_number: 23 },
    { name: 'Sergino Dest', position: 'DEF', shirt_number: 2 },
    { name: 'Chris Richards', position: 'DEF', shirt_number: 3 },
    { name: 'Mark McKenzie', position: 'DEF', shirt_number: 4 },
    { name: 'Antonee Robinson', position: 'DEF', shirt_number: 5 },
    { name: 'Tim Ream', position: 'DEF', shirt_number: 6 },
    { name: 'Joe Scally', position: 'DEF', shirt_number: 13 },
    { name: 'Miles Robinson', position: 'DEF', shirt_number: 15 },
    { name: 'Cameron Carter-Vickers', position: 'DEF', shirt_number: 22 },
    { name: 'Gio Reyna', position: 'MID', shirt_number: 7 },
    { name: 'Weston McKennie', position: 'MID', shirt_number: 8 },
    { name: 'Christian Pulisic', position: 'MID', shirt_number: 10 },
    { name: 'Tyler Adams', position: 'MID', shirt_number: 14 },
    { name: 'Johnny Cardoso', position: 'MID', shirt_number: 16 },
    { name: 'Yunus Musah', position: 'MID', shirt_number: 17 },
    { name: 'Brenden Aaronson', position: 'MID', shirt_number: 18 },
    { name: 'Luca de la Torre', position: 'MID', shirt_number: 19 },
    { name: 'Timothy Weah', position: 'FWD', shirt_number: 9 },
    { name: 'Folarin Balogun', position: 'FWD', shirt_number: 11 },
    { name: 'Josh Sargent', position: 'FWD', shirt_number: 20 },
    { name: 'Ricardo Pepi', position: 'FWD', shirt_number: 21 },
    { name: 'Haji Wright', position: 'FWD', shirt_number: 24 },
    { name: 'Cade Cowell', position: 'FWD', shirt_number: 25 },
    { name: 'Brandon Vazquez', position: 'FWD', shirt_number: 26 },
  ],
  'Paraguay': [
    { name: 'Antony Silva', position: 'GK', shirt_number: 1 },
    { name: 'Alfaro Fernandez', position: 'GK', shirt_number: 12 },
    { name: 'Carlos Coronel', position: 'GK', shirt_number: 23 },
    { name: 'Alberto Espinola', position: 'DEF', shirt_number: 2 },
    { name: 'Omar Alderete', position: 'DEF', shirt_number: 3 },
    { name: 'Fabian Balbuena', position: 'DEF', shirt_number: 4 },
    { name: 'Gustavo Gomez', position: 'DEF', shirt_number: 5 },
    { name: 'Junior Alonso', position: 'DEF', shirt_number: 6 },
    { name: 'Matias Espinoza', position: 'DEF', shirt_number: 13 },
    { name: 'Gustavo Velazquez', position: 'DEF', shirt_number: 15 },
    { name: 'Blas Riveros', position: 'DEF', shirt_number: 22 },
    { name: 'Mathias Villasanti', position: 'MID', shirt_number: 7 },
    { name: 'Andres Cubas', position: 'MID', shirt_number: 8 },
    { name: 'Miguel Almiron', position: 'MID', shirt_number: 10 },
    { name: 'Hernan Perez', position: 'MID', shirt_number: 14 },
    { name: 'Damian Bobadilla', position: 'MID', shirt_number: 16 },
    { name: 'Alex Arce', position: 'MID', shirt_number: 17 },
    { name: 'Julio Enciso', position: 'MID', shirt_number: 18 },
    { name: 'Matias Rojas', position: 'MID', shirt_number: 19 },
    { name: 'Antonio Sanabria', position: 'FWD', shirt_number: 9 },
    { name: 'Adam Bareiro', position: 'FWD', shirt_number: 11 },
    { name: 'Ramon Sosa', position: 'FWD', shirt_number: 20 },
    { name: 'Isidro Pitta', position: 'FWD', shirt_number: 21 },
    { name: 'Marcelo Fernandez', position: 'FWD', shirt_number: 24 },
    { name: 'Diego Gomez', position: 'FWD', shirt_number: 25 },
    { name: 'Derlis Gonzalez', position: 'FWD', shirt_number: 26 },
  ],
  'Australia': [
    { name: 'Mathew Ryan', position: 'GK', shirt_number: 1 },
    { name: 'Joe Gauci', position: 'GK', shirt_number: 12 },
    { name: 'Paul Izzo', position: 'GK', shirt_number: 23 },
    { name: 'Lewis Miller', position: 'DEF', shirt_number: 2 },
    { name: 'Harry Souttar', position: 'DEF', shirt_number: 3 },
    { name: 'Kye Rowles', position: 'DEF', shirt_number: 4 },
    { name: 'Aziz Behich', position: 'DEF', shirt_number: 5 },
    { name: 'Bailey Wright', position: 'DEF', shirt_number: 6 },
    { name: 'Thomas Deng', position: 'DEF', shirt_number: 13 },
    { name: 'Cameron Burgess', position: 'DEF', shirt_number: 15 },
    { name: 'Alessandro Circati', position: 'DEF', shirt_number: 22 },
    { name: 'Jackson Irvine', position: 'MID', shirt_number: 7 },
    { name: 'Aiden ONeill', position: 'MID', shirt_number: 8 },
    { name: 'Ajdin Hrustic', position: 'MID', shirt_number: 10 },
    { name: 'Riley McGree', position: 'MID', shirt_number: 14 },
    { name: 'Keanu Baccus', position: 'MID', shirt_number: 16 },
    { name: 'Connor Metcalfe', position: 'MID', shirt_number: 17 },
    { name: 'Cam Devlin', position: 'MID', shirt_number: 18 },
    { name: 'Josh Nisbet', position: 'MID', shirt_number: 19 },
    { name: 'Jamie Maclaren', position: 'FWD', shirt_number: 9 },
    { name: 'Awer Mabil', position: 'FWD', shirt_number: 11 },
    { name: 'Martin Boyle', position: 'FWD', shirt_number: 20 },
    { name: 'Kusini Yengi', position: 'FWD', shirt_number: 21 },
    { name: 'Craig Goodwin', position: 'FWD', shirt_number: 24 },
    { name: 'Nestory Irankunda', position: 'FWD', shirt_number: 25 },
    { name: 'Garang Kuol', position: 'FWD', shirt_number: 26 },
  ],
  'Turkiye': [
    { name: 'Altay Bayindir', position: 'GK', shirt_number: 1 },
    { name: 'Ugurcan Cakir', position: 'GK', shirt_number: 12 },
    { name: 'Mert Gunok', position: 'GK', shirt_number: 23 },
    { name: 'Zeki Celik', position: 'DEF', shirt_number: 2 },
    { name: 'Merih Demiral', position: 'DEF', shirt_number: 3 },
    { name: 'Samet Akaydin', position: 'DEF', shirt_number: 4 },
    { name: 'Kaan Ayhan', position: 'DEF', shirt_number: 5 },
    { name: 'Abdulkerim Bardakci', position: 'DEF', shirt_number: 6 },
    { name: 'Ferdi Kadioglu', position: 'DEF', shirt_number: 13 },
    { name: 'Mert Muldur', position: 'DEF', shirt_number: 15 },
    { name: 'Cenk Ozkacar', position: 'DEF', shirt_number: 22 },
    { name: 'Hakan Calhanoglu', position: 'MID', shirt_number: 10 },
    { name: 'Arda Guler', position: 'MID', shirt_number: 8 },
    { name: 'Orkun Kokcu', position: 'MID', shirt_number: 7 },
    { name: 'Salih Ozcan', position: 'MID', shirt_number: 14 },
    { name: 'Ismail Yuksek', position: 'MID', shirt_number: 16 },
    { name: 'Irfan Kahveci', position: 'MID', shirt_number: 17 },
    { name: 'Kenan Yildiz', position: 'MID', shirt_number: 18 },
    { name: 'Yunus Akgun', position: 'MID', shirt_number: 19 },
    { name: 'Baris Alper Yilmaz', position: 'FWD', shirt_number: 9 },
    { name: 'Yusuf Yazici', position: 'FWD', shirt_number: 11 },
    { name: 'Enes Unal', position: 'FWD', shirt_number: 20 },
    { name: 'Cenk Tosun', position: 'FWD', shirt_number: 21 },
    { name: 'Semih Kilicsoy', position: 'FWD', shirt_number: 24 },
    { name: 'Oguz Aydin', position: 'FWD', shirt_number: 25 },
    { name: 'Bertug Yildirim', position: 'FWD', shirt_number: 26 },
  ],
